### ISSUE TITLE
Add facility to set an MWSAuthToken and pass it through to API calls

### ISSUE THREAD

**Issue by alozytskyi** [caponica/AmazonMwsComplete#15]
Hi, I want to set MWS Auth token, but it's not present in any config constants or like anywhere, except for original client libraries. Is it possible to set it somehow or I'm missing something?

**Comment by caponica** [comment]
You don't need to - you just set the access key and secret key and the library manages the authentication.

**Comment by alozytskyi** [comment]
But what if I want to do the stuff on behalf of a third party? They have to give me MWS Auth token in order to allow my app to access their resources, no?

**Comment by caponica** [comment]
Sorry, I was in a bit of a rush earlier and clearly didn't read your question properly.

This bundle doesn't currently support using an AuthToken... it's something I'll add at some point, but I use it mainly for our in-house tools so have never needed to use an AuthToken.

When will it be added? Before Christmas is extremely unlikely. In Q1 2018 should be no problem.

**Comment by caponica** [comment]
MWSAuthToken support has been added in the commit #799fe0b , please provide feedback if this is working for you and includes the functionality you require.  I don't use AuthToken myself so I can't really test it... so the code is just based on my understanding of the API docs.

**Comment by alozytskyi** [comment]
Thanks! So far as seen from my testing it seems to be working.
