### ISSUE TITLE
Can't request PARAM_REQUESTED_FROM_DATE for getReport

### ISSUE THREAD

**Issue by maykino** [caponica/AmazonMwsComplete#2]
It seems like the callRequestReport doesn't accept startDate so every request defaults to now() pretty much which doesn't generate any records in the report.

**Comment by caponica** [comment]
There was a note in `MwsFeedAndReportClientPack` that it wasn't implemented yet. I've done it now (in 4722d17) - let me know if it's working as expected.

**Comment by maykino** [comment]
Thank you very much! I'm going to test it shortly!

M.

**Comment by maykino** [comment]
Do you also mind adding report_type to callGetReportRequestList? It should
be not required by default.

Thank you

**Comment by maykino** [comment]
Actually it should be passed as an associative array something like this:

self::PARAM_REPORT_TYPE_LIST         => array('Type' => $reportType),

**Comment by caponica** [comment]
I have added these options in 7c217c0 - let me know if they all work as expected

**Comment by maykino** [comment]
I think I added them as well to my fork... Thanks anyways!

**Comment by caponica** [comment]
You know... that's what pull requests are for ;-)
