### ISSUE TITLE
How to create FbaInboundClient via MwsClientPool?

### ISSUE THREAD

**Issue by 9PEAK** [caponica/AmazonMwsComplete#28]
This is the best mws sdk I've seen.

My question is that, If I use "CaponicaAmazonMwsComplete\ClientPool\MwsClientPool" , how to create "FbaInboundClient".
It seems that there is no FbaInboundClientPack in "CaponicaAmazonMwsComplete\ClientPack\".

**Comment by sergoslav** [comment]
Hi @9PEAK, you can check my pull-request for FbaInventoryClientPack  and do it similar way.
https://github.com/caponica/AmazonMwsComplete/pull/37/commits/c03a60cd35327c235a72f5aabb31aa4581c1cf64
Good luck!

**Comment by caponica** [comment]
A recent merge added FbaInventoryClientPack and FbaInboundClientPack
