### ISSUE TITLE
MarketplaceWebService_Client - use undefined constant CURLOPT_POST

### ISSUE THREAD

**Issue by AZidai** [caponica/AmazonMwsComplete#3]
In Methods "getDefaultCurlOptions" and "configureCurlOptions"  there are constant which aren't defined:
CURLOPT_POST, CURLOPT_USERAGENT, CURLOPT_PROXY ...

**Comment by caponica** [comment]
Do you have CURL available in your PHP installation? (There will be a "Curl" section in your phpinfo if it's available)

**Comment by AZidai** [comment]
Yes, you are right, I forgot to add this on my newly installed PC. Sorry
for bother you and thank you very much

On 20 Dec 2016 16:13, "Christian Morgan" <notifications@github.com> wrote:

Do you have CURL available in your PHP installation? (There will be a
"Curl" section in your phpinfo if it's available)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/caponica/AmazonMwsComplete/issues/3#issuecomment-268268046>,
or mute the thread

**Comment by AZidai** [comment]
That was the issue in my case. Thank you very much

**Comment by caponica** [comment]
No problem :-)
