### ISSUE TITLE
Redefinition of parameter $quotaMax 

### ISSUE THREAD

**Issue by AZidai** [caponica/AmazonMwsComplete#4]
AmazonMwsComplete/src/AmazonPhpClientLibrary/MarketplaceWebServiceOrders/Model/ResponseHeaderMetadata.php

**Comment by caponica** [comment]
Hi, was this a question?

**Comment by AZidai** [comment]
There is an issue with parameters in contructor of AmazonMwsComplete/src/AmazonPhpClientLibrary/MarketplaceWebServiceOrders/Model/ResponseHeaderMetadata.php

There are two parameters with the same name. I found it also in new downloaded Amazon API.
When I tried to use MWS for Orders, I've got an issue:

PHP Fatal error:  Redefinition of parameter $quotaMax in .../vendor/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebServiceOrders/Model/ResponseHeaderMetadata.php on line 31
[2017-01-13 09:18:54] php.CRITICAL: Fatal Compile Error: Redefinition of parameter $quotaMax {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Compile Error: Redefinition of parameter $quotaMax at .../vendor/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebServiceOrders/Model/ResponseHeaderMetadata.php:31)"}

Is there anything I can do without changes in "vendor" directory?

**Comment by AZidai** [comment]
I found contribution from AdrianAdamiec to solve this issue.
Also there are good contribution from maykino on creating wrapper for Orders API, which I started to build too

**Comment by caponica** [comment]
This should now be fixed. Amazon has not updated their libraries, but I have ensured that all classes in this repo use the correct (non-conflicting) parameter names.
