### ISSUE TITLE
$searchResponse->getRawXml() returns null

### ISSUE THREAD

**Issue by maykino** [caponica/AmazonMwsComplete#41]
https://github.com/caponica/AmazonMwsComplete/blob/5d4313b7e9294bd77103d2e2c592eb7ad0efa821/src/CaponicaAmazonMwsComplete/ClientPack/MwsProductClientPack.php#L445

This returns null for most of the time for me. I replaced it with: 

$searchResponse->toXML() and it works. 

![Screen Shot 2019-08-09 at 12 50 16 PM](https://user-images.githubusercontent.com/4440410/62805254-4534c580-baa4-11e9-962c-6ec59de69d5e.png)

**Comment by caponica** [comment]
Thanks - this has been implemented in https://github.com/caponica/AmazonMwsComplete/commit/4fdab450121e88bba0aa5b39b079ce640a36d07e
