### ISSUE TITLE
Is there support for the CreateFulfillmentOrder?

### ISSUE THREAD

**Issue by maykino** [caponica/AmazonMwsComplete#5]
I don't see any "client packs" for the "FbaOutboundClient". Is it not supported yet?

**Comment by caponica** [comment]
Not yet - I've not had a need to use that myself but probably will do in the next 3-6 months.

You're welcome to add one and submit a PR ;-)

**Comment by maykino** [comment]
I'm working on it right now.

**Comment by caponica** [comment]
This is included in the new FbaOutboundClientPack
