### ISSUE TITLE
I want to delete the product but I can not

### ISSUE THREAD

**Issue by gud3** [caponica/AmazonMwsComplete#8]
I am call submitFeed in MwsFeedAndReportClient and add to request array `'FeedContent' => ['SKU' => $ sku],`.
And I get the answer "Missing stream resource.", Why does this happen? He expects a file from me? Here's the data that I'm passing ` [
                    'MarketplaceId',  'SellerId', 'MWSAuthToken',
                    'FeedContent' => ['SKU' => $sku],
                    'FeedType' => '_POST_PRODUCT_DATA_',
                    'OperationType' => 'Delete',
                ]`

**Comment by bretto36** [comment]
The feed content is supposed to be the full xml message stored as a stream resource

```
$handle = fopen('php://temp/maxmemory:25600', 'r+');
fputs($handle, $xml);
rewind($handle);
```
